server:
  port: 9982
spring: 
  profiles: 
    active: ${active:local}
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  jackson: 
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding: 
      charset: UTF-8
      force: true
      enabled: true
    multipart: 
      max-file-size: 52428800
      max-request-size: 52428800
  application: 
    name: db-service
logging:
  config: classpath:logback.xml
  level:
    com.system.dao: warn 
    c.system.dao: warn
login:
  users: 
    - Noah: e10adc3949ba59abbe56e057f20f883e
    - admin: e10adc3949ba59abbe56e057f20f883e