flyway:
  enabled: false
  locations: filesystem:${locations_pre_path:/var/logs/db_locations}/dev
  baseline-on-migrate: true
  validate-on-migrate: false


databases_sync:
  name_spaces:
    source:
      datasource:
        url: ${source_1_url:jdbc:mysql://172.16.16.128:3306/database_name?characterEncoding=utf-8&useSSL=false}
        username: ${source_1_username:root}
        password: ${source_1_password:123456}
        driver-class-name: com.mysql.jdbc.Driver
    target:
      datasource:
        url: ${target_1_url:jdbc:mysql://127.0.0.1:3306/database_name?characterEncoding=utf-8&useSSL=false}
        username: ${target_1_username:root}
        password: ${target_1_password:123456}
        driver-class-name: com.mysql.jdbc.Driver
