flyway:
  enabled: false
  locations: filesystem:${locations_pre_path:/var/logs/db_locations}/test
  baseline-on-migrate: true
  validate-on-migrate: false
    
# 如果要配置多个数据库，请按命令规则 sync_source_【数据库名】:  sync_target_【数据库名】source_1_url。。。 
sync_source_shuangshi: 
  datasource:
    url: ${source_1_url:jdbc:mysql://172.16.16.128:3306/shuangshi?characterEncoding=utf-8&useSSL=false}
    username: ${source_1_username:root}
    password: ${source_1_password:tengyue360}
    driver-class-name: com.mysql.jdbc.Driver
sync_target_shuangshi: 
  datasource:
    url: ${target_1_url:jdbc:mysql://127.0.0.1:3306/shuangshi?characterEncoding=utf-8&useSSL=false}
    username: ${target_1_username:root}
    password: ${target_1_password:tengyue360}
    driver-class-name: com.mysql.jdbc.Driver
